# general
dataset: credit-a
log: e
eager: False

# data params
corrp: False
corr: False
cat: False
nc: 24
nr: 4
nw: 0
pred: 0.55
weak_pred: 0.6
N: 1000

# model, other params
fields:
- auc
- acc
- wts_ent
- wts_l1
- wts_l1_linf
- wts_1pct
- g_ent
- f_g_ent

perturb_frac: 1.0
test_perturb_frac: 0.0
perturb_norm_bound: 0.0
perturb_norm_order: -1
std: False
epochs: 200
activation: sigmoid
batch_size: 20
adv_reg_lambda: 0.0
clean_pre_train: 0.0
lr: 0.01
l1_reg: 0.0
l2_reg: 0.0
multi_gpu: False

grid:
  l1_reg:
  - 0.1
  - 0.5
  - 2.0
  - 10.0
  - 100.0
